### ISSUE TITLE
为啥我add的是时候  gradle 版本会去加载2.14.1  

### ISSUE THREAD

**Issue by timren0914** [Natjs/weex-nat-camera#2]
本地的环境和gradle wrapper都是 3.3

**Comment by acathur** [comment]
和weex使用的gradle版本有关

https://github.com/apache/incubator-weex/blob/d1d396e925ac010e331269cf51ad110b3383d7aa/android/playground/gradle/wrapper/gradle-wrapper.properties

https://github.com/apache/incubator-weex/blob/d1d396e925ac010e331269cf51ad110b3383d7aa/android/sdk/gradle/wrapper/gradle-wrapper.properties
