### ISSUE TITLE
camera.captureVideo' is undefined

### ISSUE THREAD

**Issue by 501956430** [Natjs/weex-nat-camera#4]
已经在initWeexSDK:
[WXSDKEngine registerModule:@"camera" withClass:[NatCamera class]];

<img width="585" alt="2017-07-08 22 52 19" src="https://user-images.githubusercontent.com/20204491/27986306-42b3dd22-6430-11e7-9c77-d41b07d7df60.png">

**Comment by yuan-gao** [comment]
你解决了吗？这个问题

**Comment by acathur** [comment]
update `nat-camera` to the lastest version (>= `0.1.6`), `natjs` >= `0.0.8`

```
weex plugin remove nat-camera
weex plugin add nat-camera
```

Also, please report your issue at [nat issues](https://github.com/natjs/nat/issues), thx
