### ISSUE TITLE
不支持.vue文件啊

### ISSUE THREAD

**Issue by yuan-gao** [Natjs/weex-nat-camera#5]
Unhandled promise rejection TypeError: camera.captureImage is not a function. (In 'camera.captureImage', 'camera.captureImage' is undefined)

**Comment by acathur** [comment]
update `nat-camera` to the lastest version (>= `0.1.6`), `natjs` >= `0.0.8`

```
weex plugin remove nat-camera
weex plugin add nat-camera
```

Also, please report your issue at [nat issues](https://github.com/natjs/nat/issues), thx
