### ISSUE TITLE
关于demo

### ISSUE THREAD

**Issue by wazsq** [Natjs/weex-nat-camera#7]
大佬啊，能不能给个官方demo，文档只有js的调用方法，Android和iOS端怎么调用一脸懵逼啊

**Comment by acathur** [comment]
使用camera模块不需要改动Android和iOS端代码，具体使用示例可参考 [Nat Explorer](https://github.com/natjs/nat-explorer).

**Comment by wazsq** [comment]
好的，多谢大佬
